CoffeShop/Controllers/ProductTypesController.cs
using CoffeShop.Data;
using CoffeShop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoffeShop.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class ProductTypesController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ProductTypesController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<ProductTypes> objList = _db.ProductTypes;
            return View(objList);
        }

        //GET - CREATE
        public IActionResult Create()
        {
            return View();
        }

        //POST - CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ProductTypes obj)
        {
            if(ModelState.IsValid)
            {
                _db.ProductTypes.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(obj);
        }

        //GET - EDIT
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.ProductTypes.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        //GET - POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ProductTypes obj)
        {
            if(ModelState.IsValid)
            {
                _db.ProductTypes.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(obj);
        }

        //GET - DELETE
        public IActionResult Delete(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.ProductTypes.Find(id);
            if(obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        //POST - DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.ProductTypes.Find(id);
            if(obj == null)
            {
                return NotFound();
            }

            _db.ProductTypes.Remove(obj);
            _db.SaveChanges();
            
            return RedirectToAction("Index");
        }
    }
}

CoffeShop/Views/ProductTypes/Create.cshtml
@model CoffeShop.Models.ProductTypes

<form method="post" asp-action="Create">
    <div class="broder pb-3 pt-3">
        <div asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <h2 style="text-transform:uppercase; font-size:30px;">Napravi tip proizvoda</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-8">
            <div class="form-group row p-1">
                <div class="col-4">
                    <label asp-for="Name">Ime tipa proizvoda</label>
                </div>
                <div class="col-8">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row p-1">
                <div class="col-8 offset-4 row">
                    <div class="col">
                        <input type="submit" class="btn btn-info w-100" value="Napravi" />
                    </div>
                    <div class="col">
                        <a asp-action="Index" class="btn btn-success w-100">Nazad</a>
                    </div>
                </div>
            </div>

        </div>
    </div>


</form>

@section Scripts {
    @{ <partial name="_ValidationScriptsPartial" />}
}

CoffeShop/Views/ProductTypes/Delete.cshtml
@model CoffeShop.Models.ProductTypes

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="broder pb-3 pt-3">
        <div asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <h2 style="text-transform:uppercase; font-size:30px;">Izbriši tip proizvoda</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-8">
            <div class="form-group row p-1">
                <div class="col-4">
                    <label asp-for="Name">Ime</label>
                </div>
                <div class="col-8">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row p-1">
                <div class="col-8 offset-4 row">
                    <div class="col">
                        <input type="submit" class="btn btn-danger w-100" value="Izbriši" />
                    </div>
                    <div class="col">
                        <a asp-action="Index" class="btn btn-success w-100">Nazad</a>
                    </div>
                </div>
            </div>

        </div>
    </div>


</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

CoffeShop/Views/ProductTypes/Edit.cshtml
@model CoffeShop.Models.ProductTypes

<form method="post" asp-action="Edit">
    <input asp-for="Id" hidden />
    <div class="broder pb-3 pt-3">
        <div asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <h2 style="text-transform:uppercase; font-size:30px;">Uredi tip proizvoda</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-8">
            <div class="form-group row p-1">
                <div class="col-4">
                    <label asp-for="Name">Ime</label>
                </div>
                <div class="col-8">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row p-1">
                <div class="col-8 offset-4 row">
                    <div class="col">
                        <input type="submit" class="btn btn-info w-100" value="Uredi" />
                    </div>
                    <div class="col">
                        <a asp-action="Index" class="btn btn-success w-100">Nazad</a>
                    </div>
                </div>
            </div>

        </div>
    </div>


</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

CoffeShop/Views/ProductTypes/Index.cshtml
@model IEnumerable<CoffeShop.Models.ProductTypes>

    <div class="container pb-3 pt-3">
        <div class="row pt-4">
            <div class="col-6 p-0">
                <h2 style="text-transform:uppercase; font-size:30px;">Lista tipova proizvoda</h2>
            </div>
            <div class="col-6 text-right" style="text-align:right;">
                <a asp-controller="ProductTypes" asp-action="Create" class="btn btn-primary">
                    <i class="bi bi-plus-circle"></i>
                     Napravi novi tip proizvoda
                </a>
            </div>
        </div>
    </div>

@if (Model.Count() > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Ime tipa proizvoda</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
            <tr>
                <td>@obj.Name</td>
                <td class="text-center">
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="ProductTypes" asp-route-id="@obj.Id" asp-action="Edit" class="btn btn-primary"><i class="bi bi-pencil"></i> Uredi</a>
                    </div>
                </td>
                <td class="text-center">
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="ProductTypes" asp-route-id="@obj.Id" asp-action="Delete" class="btn btn-danger"><i class="bi bi-trash"></i> Izbriši</a>
                    </div>
                </td>
            </tr>
            }
        </tbody>
    </table>
}